# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
