# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0005_auto_20161217_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=250, unique=False),
        ),
    ]
