# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20161217_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
